[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.92.0"  # Replace with the version of Hugo you are using
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
